branch-defaults:
  default:
    environment: App-api-env
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: app-api
  branch: null
  default_ec2_keyname: keypair1
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023/6.0.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application


